use [VOLS]
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V6211' ,'Ryanair' ,05/09/2015 ,CAST('8.5' AS FLOAT) ,'Londres' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V368' ,'KLM' ,05/09/2015 ,CAST('14.0' AS FLOAT) ,'Dublin' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V6101' ,'Flybe' ,05/09/2015 ,CAST('8.2' AS FLOAT) ,'Bruxelles' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V9786' ,'Ryanair' ,05/09/2015 ,CAST('12.0' AS FLOAT) ,'Bruxelles' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V3570' ,'Ryanair' ,05/09/2015 ,CAST('11.6' AS FLOAT) ,'Paris' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V1444' ,'Ryanair' ,05/10/2015 ,CAST('13.6' AS FLOAT) ,'Bruxelles' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V6923' ,'KLM' ,05/10/2015 ,CAST('16.3' AS FLOAT) ,'Paris' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V9440' ,'KLM' ,05/10/2015 ,CAST('10.4' AS FLOAT) ,'Paris' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V3222' ,'Ryanair' ,05/10/2015 ,CAST('21.1' AS FLOAT) ,'Nantes' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V2948' ,'Ryanair' ,05/10/2015 ,CAST('0.5' AS FLOAT) ,'Paris' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V2205' ,'KLM' ,05/11/2015 ,CAST('6.4' AS FLOAT) ,'Londres' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V5325' ,'Ryanair' ,05/11/2015 ,CAST('15.2' AS FLOAT) ,'Nantes' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V2091' ,'Air France' ,05/11/2015 ,CAST('10.1' AS FLOAT) ,'Paris' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V9555' ,'Air France' ,05/11/2015 ,CAST('18.2' AS FLOAT) ,'Bruxelles' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V541' ,'Flybe' ,05/11/2015 ,CAST('1.8' AS FLOAT) ,'Paris' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V3812' ,'KLM' ,05/12/2015 ,CAST('10.2' AS FLOAT) ,'Londres' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V2062' ,'KLM' ,05/12/2015 ,CAST('21.3' AS FLOAT) ,'Nantes' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V3109' ,'Air France' ,05/12/2015 ,CAST('11.2' AS FLOAT) ,'Paris' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V6659' ,'Flybe' ,05/12/2015 ,CAST('4.4' AS FLOAT) ,'Nantes' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V5674' ,'Flybe' ,05/12/2015 ,CAST('17.4' AS FLOAT) ,'Londres' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V7438' ,'Air France' ,05/13/2015 ,CAST('16.7' AS FLOAT) ,'Paris' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V686' ,'Flybe' ,05/13/2015 ,CAST('15.6' AS FLOAT) ,'Dublin' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V1671' ,'Ryanair' ,05/13/2015 ,CAST('4.4' AS FLOAT) ,'Londres' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V2533' ,'Ryanair' ,05/13/2015 ,CAST('12.4' AS FLOAT) ,'Londres' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V7580' ,'KLM' ,05/13/2015 ,CAST('19.8' AS FLOAT) ,'Londres' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V2214' ,'Air France' ,05/14/2015 ,CAST('4.0' AS FLOAT) ,'Paris' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V2306' ,'KLM' ,05/14/2015 ,CAST('23.2' AS FLOAT) ,'Paris' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V2174' ,'Ryanair' ,05/14/2015 ,CAST('8.7' AS FLOAT) ,'Dublin' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V8380' ,'Ryanair' ,05/14/2015 ,CAST('2.3' AS FLOAT) ,'Paris' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V7655' ,'KLM' ,05/14/2015 ,CAST('11.8' AS FLOAT) ,'Paris' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V9713' ,'Air France' ,05/15/2015 ,CAST('4.6' AS FLOAT) ,'Nantes' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V8832' ,'Ryanair' ,05/15/2015 ,CAST('1.5' AS FLOAT) ,'Londres' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V4866' ,'Ryanair' ,05/15/2015 ,CAST('11.2' AS FLOAT) ,'Nantes' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V5166' ,'Ryanair' ,05/15/2015 ,CAST('5.3' AS FLOAT) ,'Nantes' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V5074' ,'Air France' ,05/15/2015 ,CAST('0.3' AS FLOAT) ,'Bruxelles' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V8871' ,'Ryanair' ,05/16/2015 ,CAST('6.2' AS FLOAT) ,'Nantes' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V247' ,'Flybe' ,05/16/2015 ,CAST('19.6' AS FLOAT) ,'Paris' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V4535' ,'Flybe' ,05/16/2015 ,CAST('5.5' AS FLOAT) ,'Londres' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V5141' ,'KLM' ,05/16/2015 ,CAST('14.5' AS FLOAT) ,'Dublin' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V5923' ,'Flybe' ,05/16/2015 ,CAST('0.7' AS FLOAT) ,'Bruxelles' ,'Paris' );
