use [VOLS]
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V9000' ,'Air France' ,CAST('05/09/2015' AS DATETIME) ,CAST('0.7' AS FLOAT) ,'Dublin' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V5536' ,'Flybe' ,CAST('05/09/2015' AS DATETIME) ,CAST('18.3' AS FLOAT) ,'Nantes' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V8076' ,'Ryanair' ,CAST('05/09/2015' AS DATETIME) ,CAST('6.6' AS FLOAT) ,'Nantes' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V4546' ,'KLM' ,CAST('05/09/2015' AS DATETIME) ,CAST('11.4' AS FLOAT) ,'Nantes' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V5887' ,'Ryanair' ,CAST('05/09/2015' AS DATETIME) ,CAST('5.3' AS FLOAT) ,'Londres' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V4885' ,'Ryanair' ,CAST('05/10/2015' AS DATETIME) ,CAST('2.8' AS FLOAT) ,'Dublin' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V2552' ,'Flybe' ,CAST('05/10/2015' AS DATETIME) ,CAST('6.6' AS FLOAT) ,'Nantes' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V7060' ,'Air France' ,CAST('05/10/2015' AS DATETIME) ,CAST('16.8' AS FLOAT) ,'Bruxelles' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V2775' ,'Ryanair' ,CAST('05/10/2015' AS DATETIME) ,CAST('19.8' AS FLOAT) ,'Dublin' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V7019' ,'Air France' ,CAST('05/10/2015' AS DATETIME) ,CAST('18.3' AS FLOAT) ,'Paris' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V6605' ,'Air France' ,CAST('05/11/2015' AS DATETIME) ,CAST('23.7' AS FLOAT) ,'Londres' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V75' ,'KLM' ,CAST('05/11/2015' AS DATETIME) ,CAST('0.2' AS FLOAT) ,'Bruxelles' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V1117' ,'Air France' ,CAST('05/11/2015' AS DATETIME) ,CAST('21.8' AS FLOAT) ,'Paris' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V5267' ,'KLM' ,CAST('05/11/2015' AS DATETIME) ,CAST('13.7' AS FLOAT) ,'Dublin' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V7753' ,'KLM' ,CAST('05/11/2015' AS DATETIME) ,CAST('3.4' AS FLOAT) ,'Nantes' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V5633' ,'Air France' ,CAST('05/12/2015' AS DATETIME) ,CAST('11.4' AS FLOAT) ,'Bruxelles' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V1505' ,'Ryanair' ,CAST('05/12/2015' AS DATETIME) ,CAST('2.1' AS FLOAT) ,'Paris' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V2622' ,'Ryanair' ,CAST('05/12/2015' AS DATETIME) ,CAST('18.2' AS FLOAT) ,'Bruxelles' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V7134' ,'Ryanair' ,CAST('05/12/2015' AS DATETIME) ,CAST('5.8' AS FLOAT) ,'Londres' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V9121' ,'Ryanair' ,CAST('05/12/2015' AS DATETIME) ,CAST('13.6' AS FLOAT) ,'Bruxelles' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V964' ,'Ryanair' ,CAST('05/13/2015' AS DATETIME) ,CAST('10.5' AS FLOAT) ,'Londres' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V4338' ,'Air France' ,CAST('05/13/2015' AS DATETIME) ,CAST('10.1' AS FLOAT) ,'Bruxelles' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V8573' ,'Flybe' ,CAST('05/13/2015' AS DATETIME) ,CAST('0.1' AS FLOAT) ,'Paris' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V3783' ,'Air France' ,CAST('05/13/2015' AS DATETIME) ,CAST('4.4' AS FLOAT) ,'Dublin' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V5674' ,'Air France' ,CAST('05/13/2015' AS DATETIME) ,CAST('6.3' AS FLOAT) ,'Paris' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V3156' ,'KLM' ,CAST('05/14/2015' AS DATETIME) ,CAST('14.4' AS FLOAT) ,'Dublin' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V6541' ,'Flybe' ,CAST('05/14/2015' AS DATETIME) ,CAST('12.4' AS FLOAT) ,'Nantes' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V8948' ,'Ryanair' ,CAST('05/14/2015' AS DATETIME) ,CAST('15.3' AS FLOAT) ,'Dublin' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V9177' ,'Ryanair' ,CAST('05/14/2015' AS DATETIME) ,CAST('2.7' AS FLOAT) ,'Nantes' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V2845' ,'KLM' ,CAST('05/14/2015' AS DATETIME) ,CAST('5.4' AS FLOAT) ,'Paris' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V1106' ,'KLM' ,CAST('05/15/2015' AS DATETIME) ,CAST('11.7' AS FLOAT) ,'Nantes' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V1640' ,'Air France' ,CAST('05/15/2015' AS DATETIME) ,CAST('7.2' AS FLOAT) ,'Londres' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V6985' ,'KLM' ,CAST('05/15/2015' AS DATETIME) ,CAST('13.3' AS FLOAT) ,'Nantes' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V503' ,'Ryanair' ,CAST('05/15/2015' AS DATETIME) ,CAST('3.4' AS FLOAT) ,'Bruxelles' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V3863' ,'Air France' ,CAST('05/15/2015' AS DATETIME) ,CAST('23.5' AS FLOAT) ,'Dublin' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V1031' ,'KLM' ,CAST('05/16/2015' AS DATETIME) ,CAST('8.0' AS FLOAT) ,'Nantes' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V2739' ,'Air France' ,CAST('05/16/2015' AS DATETIME) ,CAST('6.2' AS FLOAT) ,'Nantes' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V9565' ,'KLM' ,CAST('05/16/2015' AS DATETIME) ,CAST('1.6' AS FLOAT) ,'Nantes' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V3573' ,'KLM' ,CAST('05/16/2015' AS DATETIME) ,CAST('20.5' AS FLOAT) ,'Bruxelles' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V7878' ,'Flybe' ,CAST('05/16/2015' AS DATETIME) ,CAST('7.0' AS FLOAT) ,'Nantes' ,'Nantes' );
