use [VOLS]
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V8248' ,'Flybe' ,CAST('05/10/2015' AS DATETIME) ,CAST('7.2' AS FLOAT) ,'Dublin' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V6901' ,'KLM' ,CAST('05/10/2015' AS DATETIME) ,CAST('14.7' AS FLOAT) ,'Bruxelles' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V3662' ,'Ryanair' ,CAST('05/10/2015' AS DATETIME) ,CAST('16.2' AS FLOAT) ,'Nantes' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V4159' ,'KLM' ,CAST('05/10/2015' AS DATETIME) ,CAST('16.1' AS FLOAT) ,'Bruxelles' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V4531' ,'Ryanair' ,CAST('05/10/2015' AS DATETIME) ,CAST('10.1' AS FLOAT) ,'Nantes' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V233' ,'Ryanair' ,CAST('05/11/2015' AS DATETIME) ,CAST('4.7' AS FLOAT) ,'Nantes' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V379' ,'KLM' ,CAST('05/11/2015' AS DATETIME) ,CAST('19.0' AS FLOAT) ,'Paris' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V732' ,'Air France' ,CAST('05/11/2015' AS DATETIME) ,CAST('21.8' AS FLOAT) ,'Londres' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V211' ,'Air France' ,CAST('05/11/2015' AS DATETIME) ,CAST('19.2' AS FLOAT) ,'Nantes' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V1456' ,'Flybe' ,CAST('05/11/2015' AS DATETIME) ,CAST('14.0' AS FLOAT) ,'Londres' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V7349' ,'Ryanair' ,CAST('05/12/2015' AS DATETIME) ,CAST('21.2' AS FLOAT) ,'Paris' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V3305' ,'KLM' ,CAST('05/12/2015' AS DATETIME) ,CAST('4.8' AS FLOAT) ,'Londres' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V8801' ,'Flybe' ,CAST('05/12/2015' AS DATETIME) ,CAST('8.2' AS FLOAT) ,'Dublin' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V6296' ,'KLM' ,CAST('05/12/2015' AS DATETIME) ,CAST('1.8' AS FLOAT) ,'Dublin' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V8957' ,'Ryanair' ,CAST('05/12/2015' AS DATETIME) ,CAST('20.3' AS FLOAT) ,'Paris' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V3475' ,'KLM' ,CAST('05/13/2015' AS DATETIME) ,CAST('5.7' AS FLOAT) ,'Londres' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V305' ,'Air France' ,CAST('05/13/2015' AS DATETIME) ,CAST('0.1' AS FLOAT) ,'Londres' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V8953' ,'Flybe' ,CAST('05/13/2015' AS DATETIME) ,CAST('1.7' AS FLOAT) ,'Nantes' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V3033' ,'Ryanair' ,CAST('05/13/2015' AS DATETIME) ,CAST('23.1' AS FLOAT) ,'Bruxelles' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V8461' ,'KLM' ,CAST('05/13/2015' AS DATETIME) ,CAST('4.4' AS FLOAT) ,'Bruxelles' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V7088' ,'KLM' ,CAST('05/14/2015' AS DATETIME) ,CAST('3.0' AS FLOAT) ,'Londres' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V7653' ,'Flybe' ,CAST('05/14/2015' AS DATETIME) ,CAST('14.7' AS FLOAT) ,'Paris' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V8221' ,'Flybe' ,CAST('05/14/2015' AS DATETIME) ,CAST('9.8' AS FLOAT) ,'Londres' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V7031' ,'Ryanair' ,CAST('05/14/2015' AS DATETIME) ,CAST('19.5' AS FLOAT) ,'Dublin' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V3045' ,'KLM' ,CAST('05/14/2015' AS DATETIME) ,CAST('19.2' AS FLOAT) ,'Paris' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V1480' ,'Air France' ,CAST('05/15/2015' AS DATETIME) ,CAST('0.4' AS FLOAT) ,'Paris' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V7813' ,'Ryanair' ,CAST('05/15/2015' AS DATETIME) ,CAST('12.1' AS FLOAT) ,'Bruxelles' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V8138' ,'Flybe' ,CAST('05/15/2015' AS DATETIME) ,CAST('17.0' AS FLOAT) ,'Nantes' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V7458' ,'Ryanair' ,CAST('05/15/2015' AS DATETIME) ,CAST('22.4' AS FLOAT) ,'Londres' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V4712' ,'Air France' ,CAST('05/15/2015' AS DATETIME) ,CAST('20.7' AS FLOAT) ,'Paris' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V7431' ,'Ryanair' ,CAST('05/16/2015' AS DATETIME) ,CAST('23.1' AS FLOAT) ,'Londres' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V4664' ,'KLM' ,CAST('05/16/2015' AS DATETIME) ,CAST('7.6' AS FLOAT) ,'Paris' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V178' ,'Ryanair' ,CAST('05/16/2015' AS DATETIME) ,CAST('2.4' AS FLOAT) ,'Paris' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V5668' ,'Air France' ,CAST('05/16/2015' AS DATETIME) ,CAST('4.2' AS FLOAT) ,'Londres' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V2628' ,'Flybe' ,CAST('05/16/2015' AS DATETIME) ,CAST('9.1' AS FLOAT) ,'Bruxelles' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V7070' ,'KLM' ,CAST('05/17/2015' AS DATETIME) ,CAST('14.6' AS FLOAT) ,'Nantes' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V6076' ,'Ryanair' ,CAST('05/17/2015' AS DATETIME) ,CAST('7.0' AS FLOAT) ,'Londres' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V6071' ,'Air France' ,CAST('05/17/2015' AS DATETIME) ,CAST('20.6' AS FLOAT) ,'Londres' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V790' ,'Ryanair' ,CAST('05/17/2015' AS DATETIME) ,CAST('4.4' AS FLOAT) ,'Londres' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V1188' ,'Ryanair' ,CAST('05/17/2015' AS DATETIME) ,CAST('19.2' AS FLOAT) ,'Paris' ,'Bruxelles' );
