use [VOLS]
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V4534' ,'Ryanair' ,09/53/2015 ,CAST('2.2' AS FLOAT) ,'Dublin' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V9174' ,'KLM' ,09/53/2015 ,CAST('1.1' AS FLOAT) ,'Dublin' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V9011' ,'KLM' ,09/53/2015 ,CAST('16.3' AS FLOAT) ,'Dublin' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V4525' ,'Ryanair' ,09/53/2015 ,CAST('22.7' AS FLOAT) ,'Paris' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V8629' ,'KLM' ,09/53/2015 ,CAST('13.8' AS FLOAT) ,'Dublin' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V5354' ,'KLM' ,10/53/2015 ,CAST('9.3' AS FLOAT) ,'Bruxelles' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V8670' ,'Air France' ,10/53/2015 ,CAST('2.7' AS FLOAT) ,'Paris' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V2797' ,'Ryanair' ,10/53/2015 ,CAST('22.6' AS FLOAT) ,'Dublin' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V9568' ,'Ryanair' ,10/53/2015 ,CAST('2.0' AS FLOAT) ,'Dublin' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V1731' ,'Air France' ,10/53/2015 ,CAST('6.6' AS FLOAT) ,'Londres' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V7111' ,'Ryanair' ,11/53/2015 ,CAST('9.2' AS FLOAT) ,'Paris' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V1809' ,'KLM' ,11/53/2015 ,CAST('16.8' AS FLOAT) ,'Nantes' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V2840' ,'KLM' ,11/53/2015 ,CAST('17.3' AS FLOAT) ,'Dublin' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V6773' ,'Air France' ,11/53/2015 ,CAST('18.5' AS FLOAT) ,'Dublin' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V4176' ,'Flybe' ,11/53/2015 ,CAST('18.6' AS FLOAT) ,'Dublin' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V6229' ,'Flybe' ,12/53/2015 ,CAST('18.1' AS FLOAT) ,'Bruxelles' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V1153' ,'Ryanair' ,12/53/2015 ,CAST('20.7' AS FLOAT) ,'Dublin' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V2647' ,'KLM' ,12/53/2015 ,CAST('14.2' AS FLOAT) ,'Dublin' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V8894' ,'Air France' ,12/53/2015 ,CAST('3.4' AS FLOAT) ,'Paris' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V2313' ,'KLM' ,12/53/2015 ,CAST('12.3' AS FLOAT) ,'Paris' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V6720' ,'Air France' ,13/53/2015 ,CAST('7.5' AS FLOAT) ,'Dublin' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V994' ,'Ryanair' ,13/53/2015 ,CAST('7.2' AS FLOAT) ,'Dublin' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V2792' ,'Flybe' ,13/53/2015 ,CAST('22.6' AS FLOAT) ,'Londres' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V8877' ,'Air France' ,13/53/2015 ,CAST('7.5' AS FLOAT) ,'Bruxelles' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V3980' ,'Air France' ,13/53/2015 ,CAST('8.4' AS FLOAT) ,'Paris' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V5358' ,'Ryanair' ,14/53/2015 ,CAST('11.7' AS FLOAT) ,'Nantes' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V1207' ,'KLM' ,14/53/2015 ,CAST('13.7' AS FLOAT) ,'Bruxelles' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V5846' ,'Ryanair' ,14/53/2015 ,CAST('22.3' AS FLOAT) ,'Bruxelles' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V1825' ,'Air France' ,14/53/2015 ,CAST('14.2' AS FLOAT) ,'Dublin' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V2377' ,'Air France' ,14/53/2015 ,CAST('19.2' AS FLOAT) ,'Paris' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V21' ,'KLM' ,15/53/2015 ,CAST('14.2' AS FLOAT) ,'Paris' ,'Paris' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V6600' ,'Air France' ,15/53/2015 ,CAST('7.8' AS FLOAT) ,'Nantes' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V2360' ,'Air France' ,15/53/2015 ,CAST('12.7' AS FLOAT) ,'Londres' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V1937' ,'Ryanair' ,15/53/2015 ,CAST('2.8' AS FLOAT) ,'Dublin' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V6991' ,'Flybe' ,15/53/2015 ,CAST('23.2' AS FLOAT) ,'Dublin' ,'Dublin' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V890' ,'KLM' ,16/53/2015 ,CAST('1.0' AS FLOAT) ,'Dublin' ,'Bruxelles' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V5057' ,'Air France' ,16/53/2015 ,CAST('21.4' AS FLOAT) ,'Bruxelles' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V37' ,'KLM' ,16/53/2015 ,CAST('3.8' AS FLOAT) ,'Londres' ,'Nantes' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V7699' ,'Flybe' ,16/53/2015 ,CAST('10.6' AS FLOAT) ,'Dublin' ,'Londres' );
INSERT INTO Vols(nomVol, compagnie, dateVol, duree, villeDepart, villeArrivee) VALUES ('V630' ,'KLM' ,16/53/2015 ,CAST('21.5' AS FLOAT) ,'Londres' ,'Nantes' );
