use [HOTELS]
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Londres N°2523' ,'Hotel de standing' ,'Londres' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Bruxelles N°2115' ,'Grand  hotel' ,'Bruxelles' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Dublin N°300' ,'Hotel de qualité' ,'Dublin' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Bruxelles N°3253' ,'Propre' ,'Bruxelles' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Paris N°3389' ,'Hotel de qualité' ,'Paris' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Londres N°321' ,'Hotel de qualité' ,'Londres' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Bruxelles N°825' ,'Propre' ,'Bruxelles' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Londres N°517' ,'Hotel de qualité' ,'Londres' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Dublin N°3405' ,'Grand  hotel' ,'Dublin' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Nantes N°2966' ,'Hotel de standing' ,'Nantes' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Bruxelles N°2965' ,'Propre' ,'Bruxelles' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Dublin N°735' ,'Hotel de qualité' ,'Dublin' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Bruxelles N°882' ,'Propre' ,'Bruxelles' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Nantes N°1420' ,'Propre' ,'Nantes' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Bruxelles N°2271' ,'Grand  hotel' ,'Bruxelles' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Dublin N°3741' ,'Hotel de qualité' ,'Dublin' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Bruxelles N°1650' ,'Propre' ,'Bruxelles' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Londres N°1375' ,'Propre' ,'Londres' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Paris N°1968' ,'Hotel de standing' ,'Paris' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Bruxelles N°3129' ,'Hotel de standing' ,'Bruxelles' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Nantes N°2045' ,'Propre' ,'Nantes' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Bruxelles N°1315' ,'Propre' ,'Bruxelles' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Dublin N°2683' ,'Grand  hotel' ,'Dublin' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Londres N°3264' ,'Hotel de standing' ,'Londres' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Londres N°586' ,'Propre' ,'Londres' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Bruxelles N°1374' ,'Hotel de standing' ,'Bruxelles' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Dublin N°3228' ,'Grand  hotel' ,'Dublin' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Paris N°3224' ,'Hotel de standing' ,'Paris' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Londres N°39' ,'Hotel de qualité' ,'Londres' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Bruxelles N°614' ,'Hotel de standing' ,'Bruxelles' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Dublin N°1679' ,'Propre' ,'Dublin' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Bruxelles N°1909' ,'Grand  hotel' ,'Bruxelles' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Nantes N°2455' ,'Hotel de qualité' ,'Nantes' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Nantes N°2144' ,'Hotel de standing' ,'Nantes' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Dublin N°3337' ,'Propre' ,'Dublin' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Paris N°2662' ,'Hotel de standing' ,'Paris' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Dublin N°1596' ,'Propre' ,'Dublin' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Paris N°3870' ,'Hotel de qualité' ,'Paris' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Paris N°1899' ,'Hotel de qualité' ,'Paris' );
INSERT INTO Hotels(nomHotel, descriptionHotel, ville) VALUES ('Hotel de Bruxelles N°126' ,'Hotel de qualité' ,'Bruxelles' );
