USE [master]
GO
/****** Object:  Database [CMDHOTELS]    Script Date: 07/05/2015 16:42:11 ******/
CREATE DATABASE [CMDHOTELS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CMDHOTELS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\CMDHOTELS.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CMDHOTELS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\CMDHOTELS_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [CMDHOTELS] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CMDHOTELS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CMDHOTELS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CMDHOTELS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CMDHOTELS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CMDHOTELS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CMDHOTELS] SET ARITHABORT OFF 
GO
ALTER DATABASE [CMDHOTELS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CMDHOTELS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CMDHOTELS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CMDHOTELS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CMDHOTELS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CMDHOTELS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CMDHOTELS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CMDHOTELS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CMDHOTELS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CMDHOTELS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CMDHOTELS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CMDHOTELS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CMDHOTELS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CMDHOTELS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CMDHOTELS] SET PARAMETERIZATION FORCED 
GO
ALTER DATABASE [CMDHOTELS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CMDHOTELS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CMDHOTELS] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CMDHOTELS] SET  MULTI_USER 
GO
ALTER DATABASE [CMDHOTELS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CMDHOTELS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CMDHOTELS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CMDHOTELS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [CMDHOTELS] SET DELAYED_DURABILITY = DISABLED 
GO
USE [CMDHOTELS]
GO
/****** Object:  Table [dbo].[CmdHotels]    Script Date: 07/05/2015 16:42:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CmdHotels](
	[idCmdHotel] [int] IDENTITY(1,1) NOT NULL,
	[idHotel] [int] NOT NULL,
	[date] [datetime] NOT NULL,
	[nomUtilisateur] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_CmdHotels] PRIMARY KEY CLUSTERED 
(
	[idCmdHotel] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  StoredProcedure [dbo].[sp_reservation_hotel]    Script Date: 07/05/2015 16:42:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_reservation_hotel]
	@ID_HOTEL int,
	@DATE date,
	@NOM_UTILISATEUR nvarchar(50)

AS
BEGIN
	INSERT INTO CmdHotels(idHotel, date, nomUtilisateur) VALUES (@ID_HOTEL, @DATE, @NOM_UTILISATEUR);
END

GO
USE [master]
GO
ALTER DATABASE [CMDHOTELS] SET  READ_WRITE 
GO

USE [master]
GO
/****** Object:  Database [CMDVOLS]    Script Date: 07/05/2015 16:42:32 ******/
CREATE DATABASE [CMDVOLS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CMDVOLS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\CMDVOLS.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CMDVOLS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\CMDVOLS_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [CMDVOLS] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CMDVOLS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CMDVOLS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CMDVOLS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CMDVOLS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CMDVOLS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CMDVOLS] SET ARITHABORT OFF 
GO
ALTER DATABASE [CMDVOLS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CMDVOLS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CMDVOLS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CMDVOLS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CMDVOLS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CMDVOLS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CMDVOLS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CMDVOLS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CMDVOLS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CMDVOLS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CMDVOLS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CMDVOLS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CMDVOLS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CMDVOLS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CMDVOLS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CMDVOLS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CMDVOLS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CMDVOLS] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CMDVOLS] SET  MULTI_USER 
GO
ALTER DATABASE [CMDVOLS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CMDVOLS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CMDVOLS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CMDVOLS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [CMDVOLS] SET DELAYED_DURABILITY = DISABLED 
GO
USE [CMDVOLS]
GO
/****** Object:  Table [dbo].[CmdVols]    Script Date: 07/05/2015 16:42:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CmdVols](
	[idCmdVol] [int] IDENTITY(1,1) NOT NULL,
	[idVol] [int] NOT NULL,
	[date] [datetime] NOT NULL,
	[nomUtilisateur] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_CmdVols] PRIMARY KEY CLUSTERED 
(
	[idCmdVol] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  StoredProcedure [dbo].[sp_reservation_vol]    Script Date: 07/05/2015 16:42:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_reservation_vol]
	@ID_VOL int,
	@DATE date,
	@NOM_UTILISATEUR nvarchar(50)

AS
BEGIN
	INSERT INTO CmdVols(idVol, date, nomUtilisateur) VALUES (@ID_VOL, @DATE, @NOM_UTILISATEUR);
END

GO
USE [master]
GO
ALTER DATABASE [CMDVOLS] SET  READ_WRITE 
GO

USE [master]
GO
/****** Object:  Database [HOTELS]    Script Date: 07/05/2015 15:40:01 ******/
CREATE DATABASE [HOTELS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HOTELS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\HOTELS .mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HOTELS _log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\HOTELS _log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [HOTELS] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HOTELS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [HOTELS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HOTELS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HOTELS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HOTELS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HOTELS] SET ARITHABORT OFF 
GO
ALTER DATABASE [HOTELS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [HOTELS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HOTELS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HOTELS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HOTELS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HOTELS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HOTELS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HOTELS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HOTELS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HOTELS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [HOTELS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HOTELS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HOTELS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [HOTELS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [HOTELS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HOTELS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [HOTELS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [HOTELS] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [HOTELS] SET  MULTI_USER 
GO
ALTER DATABASE [HOTELS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [HOTELS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [HOTELS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [HOTELS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [HOTELS] SET DELAYED_DURABILITY = DISABLED 
GO
USE [HOTELS]
GO
/****** Object:  Table [dbo].[Hotels]    Script Date: 07/05/2015 15:40:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Hotels](
	[idHotel] [int] IDENTITY(1,1) NOT NULL,
	[nomHotel] [nvarchar](50) NOT NULL,
	[descriptionHotel] [nvarchar](max) NOT NULL,
	[ville] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Hotels] PRIMARY KEY CLUSTERED 
(
	[idHotel] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  StoredProcedure [dbo].[sp_hotel_byId]    Script Date: 07/05/2015 15:40:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_hotel_byId]
	@ID_HOTEL int
AS
BEGIN
    SELECT * FROM Hotels WHERE idHotel=@ID_HOTEL;
END

GO
/****** Object:  StoredProcedure [dbo].[sp_hotels_dispos]    Script Date: 07/05/2015 15:40:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_hotels_dispos]
	@VILLE nvarchar(50)

AS
BEGIN
	SELECT * FROM Hotels 
		WHERE ville = @VILLE;
END

GO
USE [master]
GO
ALTER DATABASE [HOTELS] SET  READ_WRITE 
GO

USE [master]
GO
/****** Object:  Database [VOLS]    Script Date: 07/05/2015 15:39:35 ******/
CREATE DATABASE [VOLS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VOLS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\VOLS.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'VOLS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\VOLS_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [VOLS] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VOLS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [VOLS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [VOLS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [VOLS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [VOLS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [VOLS] SET ARITHABORT OFF 
GO
ALTER DATABASE [VOLS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [VOLS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [VOLS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [VOLS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [VOLS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [VOLS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [VOLS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [VOLS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [VOLS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [VOLS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [VOLS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [VOLS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [VOLS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [VOLS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [VOLS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [VOLS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [VOLS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [VOLS] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [VOLS] SET  MULTI_USER 
GO
ALTER DATABASE [VOLS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [VOLS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [VOLS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [VOLS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [VOLS] SET DELAYED_DURABILITY = DISABLED 
GO
USE [VOLS]
GO
/****** Object:  Table [dbo].[Vols]    Script Date: 07/05/2015 15:39:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Vols](
	[idVol] [int] IDENTITY(1,1) NOT NULL,
	[nomVol] [nvarchar](50) NOT NULL,
	[companie] [nvarchar](50) NOT NULL,
	[dateVol] [datetime] NOT NULL,
	[duree] [float] NOT NULL,
	[villeDepart] [nvarchar](50) NOT NULL,
	[villeArrivee] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Vols] PRIMARY KEY CLUSTERED 
(
	[idVol] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  StoredProcedure [dbo].[sp_villesArrivee]    Script Date: 07/05/2015 15:39:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_villesArrivee]
AS
BEGIN
	SELECT DISTINCT villeArrivee FROM Vols;
END

GO
/****** Object:  StoredProcedure [dbo].[sp_villesDepart]    Script Date: 07/05/2015 15:39:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_villesDepart]
AS
BEGIN
	SELECT DISTINCT villeDepart FROM Vols;
END

GO
/****** Object:  StoredProcedure [dbo].[sp_vol_byId]    Script Date: 07/05/2015 15:39:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_vol_byId]
	@ID_VOL int

AS
BEGIN
	SELECT * FROM Vols 
		WHERE idVol = @ID_VOL;
END

GO
/****** Object:  StoredProcedure [dbo].[sp_vols_dispos]    Script Date: 07/05/2015 15:39:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_vols_dispos]
	@VILLE_DEPART nvarchar(50),
	@VILLE_ARRIVEE nvarchar(50),
	@DATE datetime

AS
BEGIN
	SELECT * FROM Vols 
		WHERE villeArrivee = @VILLE_ARRIVEE AND villeDepart = @VILLE_DEPART AND dateVol = @DATE;
END

GO
USE [master]
GO
ALTER DATABASE [VOLS] SET  READ_WRITE 
GO
