//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace FlightBooking.ServiceVols {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSVolsSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MarshalByRefObject))]
    public partial class WSVols : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getVolsDisponiblesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVolOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVillesDepartOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVillesArriveeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSVols() {
            this.Url = global::FlightBooking.Properties.Settings.Default.FlightBooking_ServiceVols_WSVols;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getVolsDisponiblesCompletedEventHandler getVolsDisponiblesCompleted;
        
        /// <remarks/>
        public event getVolCompletedEventHandler getVolCompleted;
        
        /// <remarks/>
        public event getVillesDepartCompletedEventHandler getVillesDepartCompleted;
        
        /// <remarks/>
        public event getVillesArriveeCompletedEventHandler getVillesArriveeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getVolsDisponibles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public resVol[] getVolsDisponibles(string villeDepart, string villeArrivee, System.DateTime date) {
            object[] results = this.Invoke("getVolsDisponibles", new object[] {
                        villeDepart,
                        villeArrivee,
                        date});
            return ((resVol[])(results[0]));
        }
        
        /// <remarks/>
        public void getVolsDisponiblesAsync(string villeDepart, string villeArrivee, System.DateTime date) {
            this.getVolsDisponiblesAsync(villeDepart, villeArrivee, date, null);
        }
        
        /// <remarks/>
        public void getVolsDisponiblesAsync(string villeDepart, string villeArrivee, System.DateTime date, object userState) {
            if ((this.getVolsDisponiblesOperationCompleted == null)) {
                this.getVolsDisponiblesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVolsDisponiblesOperationCompleted);
            }
            this.InvokeAsync("getVolsDisponibles", new object[] {
                        villeDepart,
                        villeArrivee,
                        date}, this.getVolsDisponiblesOperationCompleted, userState);
        }
        
        private void OngetVolsDisponiblesOperationCompleted(object arg) {
            if ((this.getVolsDisponiblesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVolsDisponiblesCompleted(this, new getVolsDisponiblesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getVol", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public resVol getVol(int idVol) {
            object[] results = this.Invoke("getVol", new object[] {
                        idVol});
            return ((resVol)(results[0]));
        }
        
        /// <remarks/>
        public void getVolAsync(int idVol) {
            this.getVolAsync(idVol, null);
        }
        
        /// <remarks/>
        public void getVolAsync(int idVol, object userState) {
            if ((this.getVolOperationCompleted == null)) {
                this.getVolOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVolOperationCompleted);
            }
            this.InvokeAsync("getVol", new object[] {
                        idVol}, this.getVolOperationCompleted, userState);
        }
        
        private void OngetVolOperationCompleted(object arg) {
            if ((this.getVolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVolCompleted(this, new getVolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getVillesDepart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getVillesDepart() {
            object[] results = this.Invoke("getVillesDepart", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getVillesDepartAsync() {
            this.getVillesDepartAsync(null);
        }
        
        /// <remarks/>
        public void getVillesDepartAsync(object userState) {
            if ((this.getVillesDepartOperationCompleted == null)) {
                this.getVillesDepartOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVillesDepartOperationCompleted);
            }
            this.InvokeAsync("getVillesDepart", new object[0], this.getVillesDepartOperationCompleted, userState);
        }
        
        private void OngetVillesDepartOperationCompleted(object arg) {
            if ((this.getVillesDepartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVillesDepartCompleted(this, new getVillesDepartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getVillesArrivee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getVillesArrivee() {
            object[] results = this.Invoke("getVillesArrivee", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getVillesArriveeAsync() {
            this.getVillesArriveeAsync(null);
        }
        
        /// <remarks/>
        public void getVillesArriveeAsync(object userState) {
            if ((this.getVillesArriveeOperationCompleted == null)) {
                this.getVillesArriveeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVillesArriveeOperationCompleted);
            }
            this.InvokeAsync("getVillesArrivee", new object[0], this.getVillesArriveeOperationCompleted, userState);
        }
        
        private void OngetVillesArriveeOperationCompleted(object arg) {
            if ((this.getVillesArriveeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVillesArriveeCompleted(this, new getVillesArriveeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class resVol : ServicedComponent {
        
        private int idVolField;
        
        private string nomVolField;
        
        private string compagnieField;
        
        private System.DateTime dateVolField;
        
        private double dureeField;
        
        private string villeDepartField;
        
        private string villeArriveeField;
        
        /// <remarks/>
        public int idVol {
            get {
                return this.idVolField;
            }
            set {
                this.idVolField = value;
            }
        }
        
        /// <remarks/>
        public string nomVol {
            get {
                return this.nomVolField;
            }
            set {
                this.nomVolField = value;
            }
        }
        
        /// <remarks/>
        public string compagnie {
            get {
                return this.compagnieField;
            }
            set {
                this.compagnieField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dateVol {
            get {
                return this.dateVolField;
            }
            set {
                this.dateVolField = value;
            }
        }
        
        /// <remarks/>
        public double duree {
            get {
                return this.dureeField;
            }
            set {
                this.dureeField = value;
            }
        }
        
        /// <remarks/>
        public string villeDepart {
            get {
                return this.villeDepartField;
            }
            set {
                this.villeDepartField = value;
            }
        }
        
        /// <remarks/>
        public string villeArrivee {
            get {
                return this.villeArriveeField;
            }
            set {
                this.villeArriveeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(resVol))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ServicedComponent : ContextBoundObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServicedComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(resVol))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ContextBoundObject : MarshalByRefObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextBoundObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServicedComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(resVol))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class MarshalByRefObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void getVolsDisponiblesCompletedEventHandler(object sender, getVolsDisponiblesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVolsDisponiblesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVolsDisponiblesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resVol[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resVol[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void getVolCompletedEventHandler(object sender, getVolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resVol Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resVol)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void getVillesDepartCompletedEventHandler(object sender, getVillesDepartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVillesDepartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVillesDepartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void getVillesArriveeCompletedEventHandler(object sender, getVillesArriveeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVillesArriveeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVillesArriveeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591