//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightBooking.ServiceCommandes {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCommandes.WSCommandesSoap")]
    public interface WSCommandesSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément nomUtilisateur de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reservation", ReplyAction="*")]
        FlightBooking.ServiceCommandes.reservationResponse reservation(FlightBooking.ServiceCommandes.reservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reservation", ReplyAction="*")]
        System.Threading.Tasks.Task<FlightBooking.ServiceCommandes.reservationResponse> reservationAsync(FlightBooking.ServiceCommandes.reservationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reservationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reservation", Namespace="http://tempuri.org/", Order=0)]
        public FlightBooking.ServiceCommandes.reservationRequestBody Body;
        
        public reservationRequest() {
        }
        
        public reservationRequest(FlightBooking.ServiceCommandes.reservationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class reservationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idVol;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idHotel;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nomUtilisateur;
        
        public reservationRequestBody() {
        }
        
        public reservationRequestBody(int idVol, int idHotel, System.DateTime date, string nomUtilisateur) {
            this.idVol = idVol;
            this.idHotel = idHotel;
            this.date = date;
            this.nomUtilisateur = nomUtilisateur;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reservationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reservationResponse", Namespace="http://tempuri.org/", Order=0)]
        public FlightBooking.ServiceCommandes.reservationResponseBody Body;
        
        public reservationResponse() {
        }
        
        public reservationResponse(FlightBooking.ServiceCommandes.reservationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class reservationResponseBody {
        
        public reservationResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSCommandesSoapChannel : FlightBooking.ServiceCommandes.WSCommandesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSCommandesSoapClient : System.ServiceModel.ClientBase<FlightBooking.ServiceCommandes.WSCommandesSoap>, FlightBooking.ServiceCommandes.WSCommandesSoap {
        
        public WSCommandesSoapClient() {
        }
        
        public WSCommandesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSCommandesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCommandesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCommandesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightBooking.ServiceCommandes.reservationResponse FlightBooking.ServiceCommandes.WSCommandesSoap.reservation(FlightBooking.ServiceCommandes.reservationRequest request) {
            return base.Channel.reservation(request);
        }
        
        public void reservation(int idVol, int idHotel, System.DateTime date, string nomUtilisateur) {
            FlightBooking.ServiceCommandes.reservationRequest inValue = new FlightBooking.ServiceCommandes.reservationRequest();
            inValue.Body = new FlightBooking.ServiceCommandes.reservationRequestBody();
            inValue.Body.idVol = idVol;
            inValue.Body.idHotel = idHotel;
            inValue.Body.date = date;
            inValue.Body.nomUtilisateur = nomUtilisateur;
            FlightBooking.ServiceCommandes.reservationResponse retVal = ((FlightBooking.ServiceCommandes.WSCommandesSoap)(this)).reservation(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FlightBooking.ServiceCommandes.reservationResponse> FlightBooking.ServiceCommandes.WSCommandesSoap.reservationAsync(FlightBooking.ServiceCommandes.reservationRequest request) {
            return base.Channel.reservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<FlightBooking.ServiceCommandes.reservationResponse> reservationAsync(int idVol, int idHotel, System.DateTime date, string nomUtilisateur) {
            FlightBooking.ServiceCommandes.reservationRequest inValue = new FlightBooking.ServiceCommandes.reservationRequest();
            inValue.Body = new FlightBooking.ServiceCommandes.reservationRequestBody();
            inValue.Body.idVol = idVol;
            inValue.Body.idHotel = idHotel;
            inValue.Body.date = date;
            inValue.Body.nomUtilisateur = nomUtilisateur;
            return ((FlightBooking.ServiceCommandes.WSCommandesSoap)(this)).reservationAsync(inValue);
        }
    }
}
