//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightBooking.ServiceHotels {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceHotels.WSHotelsSoap")]
    public interface WSHotelsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHotelsDisponibles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        FlightBooking.ServiceHotels.resHotel[] getHotelsDisponibles(string ville);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHotelsDisponibles", ReplyAction="*")]
        System.Threading.Tasks.Task<FlightBooking.ServiceHotels.resHotel[]> getHotelsDisponiblesAsync(string ville);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHotel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        FlightBooking.ServiceHotels.resHotel getHotel(int idHotel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHotel", ReplyAction="*")]
        System.Threading.Tasks.Task<FlightBooking.ServiceHotels.resHotel> getHotelAsync(int idHotel);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class resHotel : ServicedComponent {
        
        private int idHotelField;
        
        private string nomHotelField;
        
        private string descriptionHotelField;
        
        private string villeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int idHotel {
            get {
                return this.idHotelField;
            }
            set {
                this.idHotelField = value;
                this.RaisePropertyChanged("idHotel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nomHotel {
            get {
                return this.nomHotelField;
            }
            set {
                this.nomHotelField = value;
                this.RaisePropertyChanged("nomHotel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string descriptionHotel {
            get {
                return this.descriptionHotelField;
            }
            set {
                this.descriptionHotelField = value;
                this.RaisePropertyChanged("descriptionHotel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ville {
            get {
                return this.villeField;
            }
            set {
                this.villeField = value;
                this.RaisePropertyChanged("ville");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(resHotel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ServicedComponent : ContextBoundObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServicedComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(resHotel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ContextBoundObject : MarshalByRefObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContextBoundObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServicedComponent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(resHotel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class MarshalByRefObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSHotelsSoapChannel : FlightBooking.ServiceHotels.WSHotelsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSHotelsSoapClient : System.ServiceModel.ClientBase<FlightBooking.ServiceHotels.WSHotelsSoap>, FlightBooking.ServiceHotels.WSHotelsSoap {
        
        public WSHotelsSoapClient() {
        }
        
        public WSHotelsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSHotelsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSHotelsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSHotelsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FlightBooking.ServiceHotels.resHotel[] getHotelsDisponibles(string ville) {
            return base.Channel.getHotelsDisponibles(ville);
        }
        
        public System.Threading.Tasks.Task<FlightBooking.ServiceHotels.resHotel[]> getHotelsDisponiblesAsync(string ville) {
            return base.Channel.getHotelsDisponiblesAsync(ville);
        }
        
        public FlightBooking.ServiceHotels.resHotel getHotel(int idHotel) {
            return base.Channel.getHotel(idHotel);
        }
        
        public System.Threading.Tasks.Task<FlightBooking.ServiceHotels.resHotel> getHotelAsync(int idHotel) {
            return base.Channel.getHotelAsync(idHotel);
        }
    }
}
